artifacts: 
  artifacts_dir: artifacts
  pickle_format_data_dir: pickle_format_data
  img_pickle_file_name: img_PICKLE_file.pkl
  feature_extraction_dir: extracted_features
  extracted_features_name: embedding.pkl
  upload_image_dir: uploads
  celeb_name: celebs data\file.txt
  clean_image_dir: cleaned_images